=== stepanovdg/EpamProject1/XML/initVeget.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="vegetables">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="vegetable"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="generalvegetable">
        <xs:sequence>
            <xs:element ref="uid"/>
            <xs:element ref="country"/>
            <xs:element ref="data"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
    <xs:complexType name="veget">
        <xs:complexContent>
            <xs:extension base="generalvegetable">
                <xs:sequence>
                    <xs:element ref="weight-per-kg"/>
                    <xs:element ref="price-per-kg"/>
                    <xs:element ref="quality-of-veget"/>
                    <xs:element ref="uniq-parameter"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="vegetable" type="veget"/>
    <xs:element name="uid">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                 <xs:length value="9"/>
                <xs:pattern value="[a-z][0-9]{8}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="country" type="xs:NCName"/>
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="year"/>
                <xs:element ref="month"/>
                <xs:element ref="day"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="year" type="xs:gYear"/>
    <xs:element name="month" type="xs:gMonth"/>
    <xs:element name="day" type="xs:gDay"/>
    <xs:element name="weight-per-kg" type="xs:decimal"/>
    <xs:element name="price-per-kg" type="xs:integer"/>
    <xs:element name="quality-of-veget" type="xs:NCName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Good"/>
                <xs:enumeration value="Eatable"/>
                <xs:enumeration value="Uneatable"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="uniq-parameter" type="xs:NMTOKEN"/>
</xs:schema>

=== stepanovdg/EpamProject1/XML/initVeget.xml
<?xml version="1.0" encoding="UTF-8"?>
<vegetables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="initVeget.xsd">
    <vegetable name="cabbage">
        <uid>d00000001</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--10--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.5</weight-per-kg>
        <price-per-kg>201</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>1</uniq-parameter>
    </vegetable>
    <vegetable name="dill">
        <uid>d00000002</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--09--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.6</weight-per-kg>
        <price-per-kg>202</price-per-kg>
        <quality-of-veget>Eatable</quality-of-veget>
        <uniq-parameter>str2</uniq-parameter>
    </vegetable>
    <vegetable name="mint">
        <uid>d00000003</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--08--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.7</weight-per-kg>
        <price-per-kg>203</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>str3</uniq-parameter>
    </vegetable>
    <vegetable name="tomato">
        <uid>d00000004</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--07--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.8</weight-per-kg>
        <price-per-kg>204</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>str4</uniq-parameter>
    </vegetable>
    <vegetable name="cucumber">
        <uid>d00000005</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.9</weight-per-kg>
        <price-per-kg>205</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>str5</uniq-parameter>
    </vegetable>
    <vegetable name="potatoes">
        <uid>d00000006</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>1.0</weight-per-kg>
        <price-per-kg>206</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>6</uniq-parameter>
    </vegetable>
    <vegetable name="cabbage">
        <uid>d00000007</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--10--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.5</weight-per-kg>
        <price-per-kg>201</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>1</uniq-parameter>
    </vegetable>
    <vegetable name="dill">
        <uid>d00000008</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--09--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.6</weight-per-kg>
        <price-per-kg>202</price-per-kg>
        <quality-of-veget>Eatable</quality-of-veget>
        <uniq-parameter>str2</uniq-parameter>
    </vegetable>
    <vegetable name="mint">
        <uid>d00000009</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--08--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.7</weight-per-kg>
        <price-per-kg>203</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>str3</uniq-parameter>
    </vegetable>
    <vegetable name="tomato">
        <uid>d00000010</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--07--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.8</weight-per-kg>
        <price-per-kg>204</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>str4</uniq-parameter>
    </vegetable>
    <vegetable name="cucumber">
        <uid>d00000011</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>0.9</weight-per-kg>
        <price-per-kg>205</price-per-kg>
        <quality-of-veget>Eatable</quality-of-veget>
        <uniq-parameter>str5</uniq-parameter>
    </vegetable>
    <vegetable name="potatoes">
        <uid>d00000012</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weight-per-kg>1.0</weight-per-kg>
        <price-per-kg>206</price-per-kg>
        <quality-of-veget>Good</quality-of-veget>
        <uniq-parameter>6</uniq-parameter>
    </vegetable>
</vegetables>
