=== stepanovdg/EpamProject1/src/by/bsu/veget/xml/initVeget.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="vegetables">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="vegetable"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="generalvegetable">
        <xs:sequence>
            <xs:element ref="uid"/>
            <xs:element ref="country"/>
            <xs:element ref="data"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
    <xs:complexType name="veget">
        <xs:complexContent>
            <xs:extension base="generalvegetable">
                <xs:sequence>
                    <xs:element ref="weightPerKg"/>
                    <xs:element ref="pricePerKg"/>
                    <xs:element ref="qualityOfVeget"/>
                    <xs:element ref="uniqParameter"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="vegetable" type="veget"/>
    <xs:element name="uid" type="xs:ID"/>
    <xs:element name="country" type="xs:NCName"/>
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="year"/>
                <xs:element ref="month"/>
                <xs:element ref="day"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="year" type="xs:gYear"/>
    <xs:element name="month" type="xs:gMonth"/>
    <xs:element name="day" type="xs:gDay"/>
    <xs:element name="weightPerKg" type="xs:decimal"/>
    <xs:element name="pricePerKg" type="xs:integer"/>
    <xs:element name="qualityOfVeget" type="xs:NCName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Good"/>
                <xs:enumeration value="Eatable"/>
                <xs:enumeration value="Uneatable"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="uniqParameter" type="xs:NMTOKEN"/>
</xs:schema>

=== stepanovdg/EpamProject1/initVeget.xml
<?xml version="1.0" encoding="UTF-8"?>
<vegetables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="initVeget.xsd">
    <vegetable name="cabbage">
        <uid>d00000001</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--10--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.5</weightPerKg>
        <pricePerKg>201</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>1</uniqParameter>
    </vegetable>
    <vegetable name="dill">
        <uid>d00000002</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--09--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.6</weightPerKg>
        <pricePerKg>202</pricePerKg>
        <qualityOfVeget>Eatable</qualityOfVeget>
        <uniqParameter>str2</uniqParameter>
    </vegetable>
    <vegetable name="mint">
        <uid>d00000003</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--08--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.7</weightPerKg>
        <pricePerKg>203</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>str3</uniqParameter>
    </vegetable>
    <vegetable name="tomato">
        <uid>d00000004</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--07--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.8</weightPerKg>
        <pricePerKg>204</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>str4</uniqParameter>
    </vegetable>
    <vegetable name="cucumber">
        <uid>d00000005</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.9</weightPerKg>
        <pricePerKg>205</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>str5</uniqParameter>
    </vegetable>
    <vegetable name="potatoes">
        <uid>d00000006</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weightPerKg>1.0</weightPerKg>
        <pricePerKg>206</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>6</uniqParameter>
    </vegetable>
    <vegetable name="cabbage">
        <uid>d00000007</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--10--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.5</weightPerKg>
        <pricePerKg>201</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>1</uniqParameter>
    </vegetable>
    <vegetable name="dill">
        <uid>d00000008</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--09--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.6</weightPerKg>
        <pricePerKg>202</pricePerKg>
        <qualityOfVeget>Eatable</qualityOfVeget>
        <uniqParameter>str2</uniqParameter>
    </vegetable>
    <vegetable name="mint">
        <uid>d00000009</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--08--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.7</weightPerKg>
        <pricePerKg>203</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>str3</uniqParameter>
    </vegetable>
    <vegetable name="tomato">
        <uid>d00000010</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--07--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.8</weightPerKg>
        <pricePerKg>204</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>str4</uniqParameter>
    </vegetable>
    <vegetable name="cucumber">
        <uid>d00000011</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weightPerKg>0.9</weightPerKg>
        <pricePerKg>205</pricePerKg>
        <qualityOfVeget>Eatable</qualityOfVeget>
        <uniqParameter>str5</uniqParameter>
    </vegetable>
    <vegetable name="potatoes">
        <uid>d00000012</uid>
        <country>usa</country>
        <data>
            <year>2011</year>
            <month>--06--</month>
            <day>---11</day>
        </data>
        <weightPerKg>1.0</weightPerKg>
        <pricePerKg>206</pricePerKg>
        <qualityOfVeget>Good</qualityOfVeget>
        <uniqParameter>6</uniqParameter>
    </vegetable>
</vegetables>
